"""Integration tests for POST /api/analyze with real resume files.

Requires the server running on http://127.0.0.1:8000
and test fixtures generated by create_test_files.py.
"""

import json
import os
import urllib.request
import urllib.error

BASE = "http://127.0.0.1:8000"
FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")


def _multipart_post(filepath: str, job_desc: str) -> tuple[int, dict]:
    """Send a real file via multipart/form-data POST."""
    boundary = "----IntegTestBoundary7777"
    filename = os.path.basename(filepath)

    with open(filepath, "rb") as f:
        file_data = f.read()

    # Build multipart body manually
    body = bytearray()

    # File part
    body.extend(f"--{boundary}\r\n".encode())
    body.extend(
        f'Content-Disposition: form-data; name="resume_file"; '
        f'filename="{filename}"\r\n'.encode()
    )
    body.extend(b"Content-Type: application/octet-stream\r\n\r\n")
    body.extend(file_data)
    body.extend(b"\r\n")

    # job_description part
    body.extend(f"--{boundary}\r\n".encode())
    body.extend(
        b'Content-Disposition: form-data; name="job_description"\r\n\r\n'
    )
    body.extend(job_desc.encode())
    body.extend(b"\r\n")

    body.extend(f"--{boundary}--\r\n".encode())

    req = urllib.request.Request(
        f"{BASE}/api/analyze",
        data=bytes(body),
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )

    try:
        resp = urllib.request.urlopen(req)
        return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


def _fake_multipart_post(fake_filename: str, job_desc: str) -> tuple[int, dict]:
    """Send fake file bytes (for validation error tests)."""
    boundary = "----IntegTestBoundary7777"

    body = bytearray()
    body.extend(f"--{boundary}\r\n".encode())
    body.extend(
        f'Content-Disposition: form-data; name="resume_file"; '
        f'filename="{fake_filename}"\r\n'.encode()
    )
    body.extend(b"Content-Type: application/octet-stream\r\n\r\n")
    body.extend(b"fake content")
    body.extend(b"\r\n")
    body.extend(f"--{boundary}\r\n".encode())
    body.extend(b'Content-Disposition: form-data; name="job_description"\r\n\r\n')
    body.extend(job_desc.encode())
    body.extend(b"\r\n")
    body.extend(f"--{boundary}--\r\n".encode())

    req = urllib.request.Request(
        f"{BASE}/api/analyze",
        data=bytes(body),
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )

    try:
        resp = urllib.request.urlopen(req)
        return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


# ---------- Tests ----------

def test_health_still_works():
    r = urllib.request.urlopen(f"{BASE}/api/health")
    data = json.loads(r.read())
    assert data["status"] == "ok"
    print("PASS  /api/health still works")


def test_real_pdf_with_skill_matching():
    """Sample resume contains Python, FastAPI, SQL, Docker, PostgreSQL, Git."""
    pdf_path = os.path.join(FIXTURES_DIR, "sample_resume.pdf")
    job = (
        "We are looking for a Python backend developer "
        "with FastAPI, SQL, Docker, and AWS experience."
    )
    status, data = _multipart_post(pdf_path, job)
    assert status == 200, f"Expected 200, got {status}: {data}"

    matched_names = [s["skill"] for s in data["matched_skills"]]
    missing_names = [s["skill"] for s in data["missing_skills"]]

    # Python, FastAPI, Docker should be matched
    for skill in ["Python", "FastAPI", "Docker"]:
        assert skill in matched_names, f"Expected '{skill}' in matched: {matched_names}"

    # AWS is in the job but not in the sample resume
    assert "AWS" in missing_names, f"Expected 'AWS' in missing: {missing_names}"

    assert isinstance(data["match_score"], int)
    assert 0 <= data["match_score"] <= 100
    assert "estimated score" in data["summary"]
    assert "temporary" not in data["summary"].lower()
    assert data["top_resume_matches"], "Expected vector search matches"
    top_match = data["top_resume_matches"][0]
    assert "job_requirement" in top_match
    assert "resume_chunk" in top_match
    assert "similarity_score" in top_match
    assert top_match["similarity_score"] >= 0.35
    assert "embeddings" not in data
    print(f"PASS  real PDF skill matching (matched={matched_names}, missing={missing_names})")


def test_real_docx_with_skill_matching():
    docx_path = os.path.join(FIXTURES_DIR, "sample_resume.docx")
    job = (
        "We need someone skilled in Python, PostgreSQL, "
        "and Kubernetes for our cloud infrastructure team."
    )
    status, data = _multipart_post(docx_path, job)
    assert status == 200, f"Expected 200, got {status}: {data}"

    matched_names = [s["skill"] for s in data["matched_skills"]]
    missing_names = [s["skill"] for s in data["missing_skills"]]

    assert "Python" in matched_names
    assert "PostgreSQL" in matched_names
    assert "Kubernetes" in missing_names
    assert isinstance(data["match_score"], int)
    assert 0 <= data["match_score"] <= 100
    assert "estimated score" in data["summary"]
    assert "temporary" not in data["summary"].lower()
    assert data["top_resume_matches"], "Expected vector search matches"
    top_match = data["top_resume_matches"][0]
    assert "job_requirement" in top_match
    assert "resume_chunk" in top_match
    assert "similarity_score" in top_match
    assert top_match["similarity_score"] >= 0.35
    assert "embeddings" not in data
    print(f"PASS  real DOCX skill matching (matched={matched_names}, missing={missing_names})")


def test_bad_extension_rejected():
    status, data = _fake_multipart_post(
        "resume.txt",
        "Python developer with FastAPI, SQL, Docker, and AWS experience required.",
    )
    assert status == 400
    assert "Unsupported file type" in data["detail"]
    print("PASS  bad extension rejected")


def test_short_job_description_rejected():
    pdf_path = os.path.join(FIXTURES_DIR, "sample_resume.pdf")
    status, data = _multipart_post(pdf_path, "Short")
    assert status == 400
    assert "too short" in data["detail"]
    print("PASS  short job description rejected")


def test_empty_job_description_rejected():
    pdf_path = os.path.join(FIXTURES_DIR, "sample_resume.pdf")
    status, data = _multipart_post(pdf_path, "   ")
    assert status == 400
    print("PASS  empty job description rejected")


if __name__ == "__main__":
    test_health_still_works()
    test_real_pdf_with_skill_matching()
    test_real_docx_with_skill_matching()
    test_bad_extension_rejected()
    test_short_job_description_rejected()
    test_empty_job_description_rejected()
    print("\nAll integration tests passed!")
